sonar.organization=madhav-000-s
sonar.projectKey=Madhav-000-s_demand-forecast
sonar.projectName=demand-forecast
sonar.sources=app,ml,scripts
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=junit.xml
sonar.exclusions=**/__pycache__/**
